name: Catfriends Redux CI

on:
  push:
    branches: [ "main" ]
    paths: 
    - 'cats-redux/**'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cats-redux
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./cats-redux/package-lock.json
    - run: export NODE_OPTIONS=--openssl-legacy-provider
    - run: npm install
    - run: npm run build --if-present
